"""initial migration

Revision ID: dd3ee42db3d3
Revises: None
Create Date: 2019-08-28 16:48:48.478102

"""

# revision identifiers, used by Alembic.
revision = 'dd3ee42db3d3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tmp_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp_user')
    ### end Alembic commands ###
